[exec]
shell = "/bin/bash"
bin = "./.data/scripts"

[age]
recipients = [
  "age17tvujaxf04ecgatw483s90zcfssq62lnvgupsyc7pjf8paezwd7sdmt392",
]
identity_file = "./.data/age/key.txt"


[variables]
var_files = [
  "./.data/vars/vault.toml",
  "./.data/vars/vault.toml?vault=true",
  "./.data/vars/vars.toml",
]

[[actions]]
name = "template"
template = "./.data/templates/test.txt.tmpl"
destination = "./.data/generated/test.txt"
mode = "0600"
vars = { var1 = "local.var1", var2 = "local.var2" }

[[actions]]
name = "template"
template = "./.data/templates/ssh_config.tmpl"
destination = "~/.ssh/config"
mode = "0600"

[[actions]]
name = "file.includes_text"
invert = false # when true it ensure the text is not present"
desc = "ensure ssh config file contains mmdot config"
file = "~/.ssh/config"
content = """
Host *
    include ~/.ssh/mmdot_config
"""
