[exec]
shell = "/bin/bash"
bin = "./.data/scripts"

[bundles.test]
scripts = [
  { path = "./.data/scripts/run.sh", tags = ["test"] },
  { path = "./.data/scripts/run2.sh", tags = ["test"] },
]

[bundles.personal]
scripts = [
  { path = "./.data/scripts/brew.personal.sh", tags = ["brew", "personal"] },
]

[bundles.work]
scripts = [
  { path = "./.data/scripts/brew.work.sh", tags = ["brew", "work"] },
]

[bundles.cleanup]
scripts = [
  { path = "./.data/scripts/brew.remove.sh", tags = ["brew", "cleanup"] },
]

[actions]
personal = { bundles = ["personal"] }
work = { bundles = ["work"] }
cleanup = { bundles = ["cleanup"] }
test = { bundles = ["test"] }

[templates]
jobs = [
  { template = ".data/templates/test.txt.tmpl", output = ".data/generated/test.txt", vars = { email = "test@example.com", timestamp = "2024-03-27" } },
  { template = ".data/templates/test.txt.tmpl", output = ".data/generated/test2.txt", vars = { email = "user2@example.com", timestamp = "2024-03-28" } },
]

  [templates.vars]
  user = "hayden"
  brew = { remove = true }

[brew.remove]
remove = true
outfile = "./.data/scripts/brew.remove.sh"
taps = ["remove:taps"]
brews = ["remove:brew"]
casks = ["remove:cask"]


[brew.work]
outfile = "./.data/scripts/brew.work.sh"
includes = ["all"]
taps = ["work:taps"]
brews = ["work:brews"]
casks = ["work:casks"]

[brew.personal]
outfile = "./.data/scripts/brew.personal.sh"
includes = ["all"]
taps = ["personal:taps"]
brews = ["personal:brews"]
casks = ["personal:casks"]

[brew.all]
taps = ["all:taps"]
brews = ["all:brews"]
casks = ["all:casks"]
