[exec]
shell = "/bin/bash"
bin = "./.data/scripts"

[age]
recipients = [
  "age17tvujaxf04ecgatw483s90zcfssq62lnvgupsyc7pjf8paezwd7sdmt392",
]
identity_file = "./.data/age/key.txt"


[variables]
var_files = [
  "./.data/vars/vault.toml",
  "./.data/vars/vault.toml?vault=true",
  "./.data/vars/vars.toml",
]
